
name: CI/CD Pipeline 

on:
  push:
    branches:
      - develop
env:
  DOCKER_IMAGE: "${PORTFOLIO_DOCKERIMAGE}"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: luc426
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Docker Tags
        id: docker-tags
        run: |
          SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})
          echo "TAG=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          load: false
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  update-k8s-deployment:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Deployment Image
        run: |
          git pull --rebase origin develop
          IMAGE_TAG=$(git rev-parse --short=7 ${{ github.sha }})
          sed -i 's|image: '${{ env.DOCKER_IMAGE }}':.*|image: '${{ env.DOCKER_IMAGE }}':'"$IMAGE_TAG"'|' k8s/base/deployment.yaml
          git add k8s/base/deployment.yaml
          git commit -m "Update image version to $IMAGE_TAG"
          git push